version: '3.7'
services:
  masoretic-php:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    container_name: masoretic-php
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080 -t public

  masoretic-mariadb:
    image: mariadb:10.11
    ports:
      - 3306:3306
    container_name: masoretic-mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
